#INCLUDE <P16F877A.INC>
INIT
    BANKSEL TRISA
    MOVLW   0x00a
    MOVWF   TRISA
    MOVLW   B'00110001'
    MOVWF   TRISB
    MOVLW   0x00
    MOVWF   TRISC
    MOVLW   0x00
    MOVWF   TRISD
    MOVLW   0x00
    MOVWF   TRISE
    MOVLW   0x06
    MOVWF   ADCON1
    BANKSEL PORTA
    CLRF    PORTA
    MOVLW   B'00000000'
    MOVWF   PORTB
    MOVLW   0xFF
    MOVWF   PORTC
    CLRF    PORTD
    CLRF    PORTE
    RETURN